version: '3.8'
services:
  passlock:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    environment:
      - NODE_ENV=production
    # If you have a .env file, you can uncomment the line below
    # env_file:
    #   - .env
